server:
  port: ${SERVER_PORT:8081}
spring:
  application:
    name: "solicitudes"
  devtools:
    add-properties: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
    user: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    clear-checksums: true
adapters:
  r2dbc:
    host: "${DB_HOST}"
    port: ${DB_PORT}
    database: "${DB_NAME}"
    schema: "public"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "${CORS_ALLOWED_ORIGINS}"
routes:
  paths:
    tasks: "/api/v1/solicitud"
    tasksById: "/api/v1/solicitud/{identification}"

springdoc:
  swagger-ui:
    path: "/api/doc/swagger-ui.html"
  api-docs:
    path: "/api/doc/api-docs"

jwt:
  secret: ${JWT_SECRET}

aws:
  sqs:
    notificationsQueueName: ${AWS_SQS_NOTIFICATIONS_QUEUE_NAME}
    loanValidationQueueName: ${AWS_SQS_VALIDATION_QUEUE_NAME}
    loanApprovedCountQueueName: ${AWS_SQS_COUNT_APPROVED_QUEUE_NAME}
    region: ${AWS_REGION:us-east-1}
    callBack: ${AWS_CALLBACK}