server:
  port: 8081
spring:
  application:
    name: "solicitudes"
  devtools:
    add-properties: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    url: "jdbc:postgresql://db_solicitudes:5432/solicitudes_db"
    user: "postgres"
    password: "Misional123@"
    clear-checksums: true
adapters:
  r2dbc:
    host: "db_solicitudes"
    port: 5432
    database: "solicitudes_db"
    schema: "public"
    username: "postgres"
    password: "Misional123@"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4201,http://localhost:8081"

routes:
  paths:
    tasks: "/api/v1/solicitud"
    tasksById: "/api/v1/solicitud/{identification}"

springdoc:
  swagger-ui:
    path: "/api/doc/swagger-ui.html"
  api-docs:
    path: "/api/doc/api-docs"

jwt:
  secret: c3ByaW5nLWJvb3Qtand0LXRva2VuLWdlbmVyYXRpb24tc2VjcmV0LWtleS13aGF0ZXZlci15b3UtY2FuLXRoaW5rLW9mLXRvLW1ha2UtaXQtcmFuZG9tLWFzLXlvdS1saWtlLWFzLXRvLWJl